version: '3'

services:
  api:
    container_name: api
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - "5000:5000"
  client:
    container_name: client
    build:
      context: .
      dockerfile: Dockerfile2.txt
    ports:
      - '8000:8000'
    restart: always
    
  
